/*
 * Fuel UX Spinner
 * https://github.com/ExactTarget/fuelux
 *
 * Copyright (c) 2012 ExactTarget
 * Licensed under the MIT license.
 *
 * Version 2.3.2
 */

define(["require","jquery"],function(e){var t=e("jquery"),n=function(e,n){this.$element=t(e),this.options=t.extend({},t.fn.spinner.defaults,n),this.$input=this.$element.find(".spinner-input"),this.$element.on("keyup",this.$input,t.proxy(this.change,this)),this.options.hold?(this.$element.on("mousedown",".spinner-up",t.proxy(function(){this.startSpin(!0)},this)),this.$element.on("mouseup",".spinner-up, .spinner-down",t.proxy(this.stopSpin,this)),this.$element.on("mouseout",".spinner-up, .spinner-down",t.proxy(this.stopSpin,this)),this.$element.on("mousedown",".spinner-down",t.proxy(function(){this.startSpin(!1)},this))):(this.$element.on("click",".spinner-up",t.proxy(function(){this.step(!0)},this)),this.$element.on("click",".spinner-down",t.proxy(function(){this.step(!1)},this))),this.switches={count:1,enabled:!0},this.options.speed==="medium"?this.switches.speed=300:this.options.speed==="fast"?this.switches.speed=100:this.switches.speed=500,this.lastValue=null,this.render(),this.options.disabled&&this.disable()};n.prototype={constructor:n,render:function(){this.$input.val(this.options.value),this.$input.attr("maxlength",(this.options.max+"").split("").length)},change:function(){var e=this.$input.val();e/1?this.options.value=e/1:(e=e.replace(/[^0-9]/g,""),this.$input.val(e),this.options.value=e/1),this.triggerChangedEvent()},stopSpin:function(){clearTimeout(this.switches.timeout),this.switches.count=1,this.triggerChangedEvent()},triggerChangedEvent:function(){var e=this.value();if(e===this.lastValue)return;this.lastValue=e,this.$element.trigger("changed",e),this.$element.trigger("change")},startSpin:function(e){if(!this.options.disabled){var n=this.switches.count;n===1?(this.step(e),n=1):n<3?n=1.5:n<8?n=2.5:n=4,this.switches.timeout=setTimeout(t.proxy(function(){this.iterator(e)},this),this.switches.speed/n),this.switches.count++}},iterator:function(e){this.step(e),this.startSpin(e)},step:function(e){var t=this.options.value,n=e?this.options.max:this.options.min;if(e?t<n:t>n){var r=t+(e?1:-1)*this.options.step;(e?r>n:r<n)?this.value(n):this.value(r)}},value:function(e){return!isNaN(parseFloat(e))&&isFinite(e)?(e=parseFloat(e),this.options.value=e,this.$input.val(e),this):this.options.value},disable:function(){this.options.disabled=!0,this.$input.attr("disabled",""),this.$element.find("button").addClass("disabled")},enable:function(){this.options.disabled=!1,this.$input.removeAttr("disabled"),this.$element.find("button").removeClass("disabled")}},t.fn.spinner=function(e,r){var i,s=this.each(function(){var s=t(this),o=s.data("spinner"),u=typeof e=="object"&&e;o||s.data("spinner",o=new n(this,u)),typeof e=="string"&&(i=o[e](r))});return i===undefined?s:i},t.fn.spinner.defaults={value:1,min:1,max:999,step:1,hold:!0,speed:"medium",disabled:!1},t.fn.spinner.Constructor=n,t(function(){t("body").on("mousedown.spinner.data-api",".spinner",function(e){var n=t(this);if(n.data("spinner"))return;n.spinner(n.data())})})});