/*
 * Fuel UX Spinner
 * https://github.com/ExactTarget/fuelux
 *
 * Copyright (c) 2012 ExactTarget
 * Licensed under the MIT license.
 *
 * Version 2.3.2
 */

define(["require","jquery"],function(t){var i=t("jquery"),s=function(t,s){this.$element=i(t),this.options=i.extend({},i.fn.spinner.defaults,s),this.$input=this.$element.find(".spinner-input"),this.$element.on("keyup",this.$input,i.proxy(this.change,this)),this.options.hold?(this.$element.on("mousedown",".spinner-up",i.proxy(function(){this.startSpin(!0)},this)),this.$element.on("mouseup",".spinner-up, .spinner-down",i.proxy(this.stopSpin,this)),this.$element.on("mouseout",".spinner-up, .spinner-down",i.proxy(this.stopSpin,this)),this.$element.on("mousedown",".spinner-down",i.proxy(function(){this.startSpin(!1)},this))):(this.$element.on("click",".spinner-up",i.proxy(function(){this.step(!0)},this)),this.$element.on("click",".spinner-down",i.proxy(function(){this.step(!1)},this))),this.switches={count:1,enabled:!0},"medium"===this.options.speed?this.switches.speed=300:"fast"===this.options.speed?this.switches.speed=100:this.switches.speed=500,this.lastValue=null,this.render(),this.options.disabled&&this.disable()};s.prototype={constructor:s,render:function(){this.$input.val(this.options.value).trigger("change"),this.$input.attr("maxlength",(this.options.max+"").split("").length)},change:function(){var t=this.$input.val();t/1?this.options.value=t/1:(t=t.replace(/[^0-9]/g,""),this.$input.val(t).trigger("change"),this.options.value=t/1),this.triggerChangedEvent()},stopSpin:function(){clearTimeout(this.switches.timeout),this.switches.count=1,this.triggerChangedEvent()},triggerChangedEvent:function(){var t=this.value();t!==this.lastValue&&(this.lastValue=t,this.$element.trigger("changed",t),this.$element.trigger("change"))},startSpin:function(t){if(!this.options.disabled){var s=this.switches.count;1===s?(this.step(t),s=1):s=s<3?1.5:s<8?2.5:4,this.switches.timeout=setTimeout(i.proxy(function(){this.iterator(t)},this),this.switches.speed/s),this.switches.count++}},iterator:function(t){this.step(t),this.startSpin(t)},step:function(t){var i=this.options.value,s=t?this.options.max:this.options.min;if(t?i<s:i>s){var e=i+(t?1:-1)*this.options.step;(t?e>s:e<s)?this.value(s):this.value(e)}},value:function(t){return!isNaN(parseFloat(t))&&isFinite(t)?(t=parseFloat(t),this.options.value=t,this.$input.val(t).trigger("change"),this):this.options.value},disable:function(){this.options.disabled=!0,this.$input.attr("disabled",""),this.$element.find("button").addClass("disabled")},enable:function(){this.options.disabled=!1,this.$input.removeAttr("disabled"),this.$element.find("button").removeClass("disabled")}},i.fn.spinner=function(t,e){var n,o=this.each(function(){var o=i(this),h=o.data("spinner"),p="object"==typeof t&&t;h||o.data("spinner",h=new s(this,p)),"string"==typeof t&&(n=h[t](e))});return void 0===n?o:n},i.fn.spinner.defaults={value:1,min:1,max:999,step:1,hold:!0,speed:"medium",disabled:!1},i.fn.spinner.Constructor=s,i(function(){i("body").on("mousedown.spinner.data-api",".spinner",function(t){var s=i(this);s.data("spinner")||s.spinner(s.data())})})});