/*
 * Fuel UX Wizard
 * https://github.com/ExactTarget/fuelux
 *
 * Copyright (c) 2012 ExactTarget
 * Licensed under the MIT license.
 *
 * Version 2.3.0
 */

define(["require","jquery"],function(t){var e=t("jquery"),i=function(t,i){var n;this.$element=e(t),this.options=e.extend({},e.fn.wizard.defaults,i),this.currentStep=1,this.numSteps=this.$element.find("li").length,this.$prevBtn=this.$element.find("button.btn-prev"),this.$nextBtn=this.$element.find("button.btn-next"),n=this.$nextBtn.children().detach(),this.nextText=e.trim(this.$nextBtn.text()),this.$nextBtn.append(n),this.$prevBtn.on("click",e.proxy(this.previous,this)),this.$nextBtn.on("click",e.proxy(this.next,this)),this.$element.on("click","li.complete",e.proxy(this.stepclicked,this))};i.prototype={constructor:i,setState:function(){var t=this.currentStep>1,i=1===this.currentStep,n=this.currentStep===this.numSteps;this.$prevBtn.attr("disabled",!0===i||!1===t);var s=this.$nextBtn.data();if(s&&s.last&&(this.lastText=s.last,void 0!==this.lastText)){var r=!0!==n?this.nextText:this.lastText,a=this.$nextBtn.children().detach();this.$nextBtn.text(r).append(a)}var h=this.$element.find("li");h.removeClass("active").removeClass("complete"),h.find("span.badge").removeClass("badge-info").removeClass("badge-success");var d="li:lt("+(this.currentStep-1)+")",c=this.$element.find(d);c.addClass("complete"),c.find("span.badge").addClass("badge-success");var l="li:eq("+(this.currentStep-1)+")",p=this.$element.find(l);p.addClass("active"),p.find("span.badge").addClass("badge-info");var u=p.data().target;e(".step-pane").removeClass("active"),e(u).addClass("active"),this.$element.trigger("changed")},stepclicked:function(t){var i=e(t.currentTarget),n=e(".steps li").index(i),s=e.Event("stepclick");this.$element.trigger(s,{step:n+1}),s.isDefaultPrevented()||(this.currentStep=n+1,this.setState())},previous:function(){if(this.currentStep>1){var t=e.Event("change");if(this.$element.trigger(t,{step:this.currentStep,direction:"previous"}),t.isDefaultPrevented())return;this.currentStep-=1,this.setState()}},next:function(){var t=this.currentStep+1<=this.numSteps,i=this.currentStep===this.numSteps;if(t){var n=e.Event("change");if(this.$element.trigger(n,{step:this.currentStep,direction:"next"}),n.isDefaultPrevented())return;this.currentStep+=1,this.setState()}else i&&this.$element.trigger("finished")},selectedItem:function(t){return{step:this.currentStep}}},e.fn.wizard=function(t,n){var s,r=this.each(function(){var r=e(this),a=r.data("wizard"),h="object"==typeof t&&t;a||r.data("wizard",a=new i(this,h)),"string"==typeof t&&(s=a[t](n))});return void 0===s?r:s},e.fn.wizard.defaults={},e.fn.wizard.Constructor=i,e(function(){e("body").on("mousedown.wizard.data-api",".wizard",function(){var t=e(this);t.data("wizard")||t.wizard(t.data())})})});