/*
 * Fuel UX Wizard
 * https://github.com/ExactTarget/fuelux
 *
 * Copyright (c) 2012 ExactTarget
 * Licensed under the MIT license.
 *
 * Version 2.3.0
 */

define(["require","jquery"],function(e){var t=e("jquery"),n=function(e,n){var r;this.$element=t(e),this.options=t.extend({},t.fn.wizard.defaults,n),this.currentStep=1,this.numSteps=this.$element.find("li").length,this.$prevBtn=this.$element.find("button.btn-prev"),this.$nextBtn=this.$element.find("button.btn-next"),r=this.$nextBtn.children().detach(),this.nextText=t.trim(this.$nextBtn.text()),this.$nextBtn.append(r),this.$prevBtn.on("click",t.proxy(this.previous,this)),this.$nextBtn.on("click",t.proxy(this.next,this)),this.$element.on("click","li.complete",t.proxy(this.stepclicked,this))};n.prototype={constructor:n,setState:function(){var e=this.currentStep>1,n=this.currentStep===1,r=this.currentStep===this.numSteps;this.$prevBtn.attr("disabled",n===!0||e===!1);var i=this.$nextBtn.data();if(i&&i.last){this.lastText=i.last;if(typeof this.lastText!="undefined"){var s=r!==!0?this.nextText:this.lastText,o=this.$nextBtn.children().detach();this.$nextBtn.text(s).append(o)}}var u=this.$element.find("li");u.removeClass("active").removeClass("complete"),u.find("span.badge").removeClass("badge-info").removeClass("badge-success");var a="li:lt("+(this.currentStep-1)+")",f=this.$element.find(a);f.addClass("complete"),f.find("span.badge").addClass("badge-success");var l="li:eq("+(this.currentStep-1)+")",c=this.$element.find(l);c.addClass("active"),c.find("span.badge").addClass("badge-info");var h=c.data().target;t(".step-pane").removeClass("active"),t(h).addClass("active"),this.$element.trigger("changed")},stepclicked:function(e){var n=t(e.currentTarget),r=t(".steps li").index(n),i=t.Event("stepclick");this.$element.trigger(i,{step:r+1});if(i.isDefaultPrevented())return;this.currentStep=r+1,this.setState()},previous:function(){var e=this.currentStep>1;if(e){var n=t.Event("change");this.$element.trigger(n,{step:this.currentStep,direction:"previous"});if(n.isDefaultPrevented())return;this.currentStep-=1,this.setState()}},next:function(){var e=this.currentStep+1<=this.numSteps,n=this.currentStep===this.numSteps;if(e){var r=t.Event("change");this.$element.trigger(r,{step:this.currentStep,direction:"next"});if(r.isDefaultPrevented())return;this.currentStep+=1,this.setState()}else n&&this.$element.trigger("finished")},selectedItem:function(e){return{step:this.currentStep}}},t.fn.wizard=function(e,r){var i,s=this.each(function(){var s=t(this),o=s.data("wizard"),u=typeof e=="object"&&e;o||s.data("wizard",o=new n(this,u)),typeof e=="string"&&(i=o[e](r))});return i===undefined?s:i},t.fn.wizard.defaults={},t.fn.wizard.Constructor=n,t(function(){t("body").on("mousedown.wizard.data-api",".wizard",function(){var e=t(this);if(e.data("wizard"))return;e.wizard(e.data())})})});