/**
 * Copyright (c) 2009 Sergiy Kovalchuk (serg472@gmail.com)
 *
 * Dual licensed under the MIT (http://www.opensource.org/licenses/mit-license.php)
 * and GPL (http://www.opensource.org/licenses/gpl-license.php) licenses.
 *
 * Following code is based on Element.mask() implementation from ExtJS framework (http://extjs.com/)
 *
 * https://github.com/iloveitaly/jquery.loadmask.spin/blob/master/jquery.loadmask.spin.js
 *
 */

!function(e){e.fn.mask=function(a){return a=e.extend({spinner:{lines:10,length:4,width:2,radius:5},spinnerPadding:5,label:"",delay:0,overlayOpacity:.75,overlaySize:!1},a),e(this).each(function(){var s=e(this);a.delay>0?s.data("_mask_timeout",setTimeout(function(){e.maskElement(s,a)},a.delay)):e.maskElement(s,a)})},e.fn.unmask=function(){return e(this).each(function(){e.unmaskElement(e(this))})},e.fn.isMasked=function(){return this.hasClass("masked")},e.maskElement=function(a,s){void 0!==a.data("_mask_timeout")&&(clearTimeout(a.data("_mask_timeout")),a.removeData("_mask_timeout")),a.isMasked()&&e.unmaskElement(a),"static"==a.css("position")&&a.addClass("masked-relative"),a.addClass("masked");var t=e('<div class="loadmask"></div>').css({opacity:0});if(!1!==s.overlaySize&&(void 0!==s.overlaySize.height&&t.height(s.overlaySize.height),void 0!==s.overlaySize.width&&t.width(s.overlaySize.width)),navigator.userAgent.toLowerCase().indexOf("msie")>-1&&(t.height(a.height()+parseInt(a.css("padding-top"))+parseInt(a.css("padding-bottom"))),t.width(a.width()+parseInt(a.css("padding-left"))+parseInt(a.css("padding-right")))),navigator.userAgent.toLowerCase().indexOf("msie 6")>-1&&a.find("select").addClass("masked-hidden"),a.append(t),s.label.length>0||!1!==s.spinner){var i=e('<div class="loadmask-msg" style="display:none;"></div>').css({opacity:0});if(!1!==s.spinner&&i.append(new Spinner(s.spinner).spin().el),s.label.length>0){var n=e('<div class="loadmask-label">'+s.label+"</div>");i.append(n)}if(a.append(i),i.css("top",Math.round(t.height()/2-(i.height()-parseInt(i.css("padding-top"))-parseInt(i.css("padding-bottom")))/2)+"px"),i.css("left",Math.round(t.width()/2-(i.width()-parseInt(i.css("padding-left"))-parseInt(i.css("padding-right")))/2)+"px"),i.show(),!1!==s.spinner&&s.label.length>0){var d=2*s.spinner.radius+2*(s.spinner.width+s.spinner.length);n.css({"margin-left":d/2+s.spinnerPadding,"margin-top":-n.height()/2})}i.fadeTo("slow",1)}t.fadeTo("slow",s.overlayOpacity)},e.unmaskElement=function(e){void 0!==e.data("_mask_timeout")&&(clearTimeout(e.data("_mask_timeout")),e.removeData("_mask_timeout")),e.find(".loadmask-msg,.loadmask").remove(),e.removeClass("masked"),e.removeClass("masked-relative"),e.find("select").removeClass("masked-hidden")}}(jQuery);